apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-finops

resources:
  - ../../base
  - storage.yaml

labels:
  - pairs:
      environment: aws

# Production patches
patches:
  - path: prometheus-storage-patch.yaml
  - path: grafana-storage-patch.yaml